### PR TITLE
Simplified config parsing code by using ast.literal_eval

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Review by lukelbd — CHANGES_REQUESTED** [review]
LGTM, just need you to fix a PEP8 line too long error (in the future you can avoid this using pre-commit as [described in the contribution guide](https://proplot.readthedocs.io/en/latest/contributions.html#preparing-pull-requests)).

**Comment by lukelbd** [comment]
Although why the 2 ast.evals? When I do that with something simple like `ast.literal_eval(ast.literal_eval(ast.parse('2.1', mode='eval')))` I get an error.

**Comment by lukelbd** [comment]
Tried implementing your changes locally and couldn't get it to work (`import proplot` fails).

Honestly since rc params are constrained to have such simple values -- only boolean, string, and numeric -- I think the current approach is fine. So I think I'll close this but appreciate the suggestion. I also removed the `eval` in a recent commit.

**Comment by lukelbd** [comment]
In case you're curious the newest version (v0.8) uses matplotlib's "validators" when assigning `proplotrc` parameters to the rc dict. Some of the validators use `ast.literal_eval` internally. So conversions of proplotrc values are no longer so clunky.

**Comment by KOLANICH** [comment]
Thank you for the info.

**Pull request closed without merging**
