### PR TITLE
Permit setting 'style' to default, and add 'bbox' as 'border' alternative for inner a-b-c labels and titles

### PR DESCRIPTION
**Pull request by pratiman-91**
This is my first contribution. Let me know if there is any problem with the issue or failing any tests.

### CODE REVIEW

**Comment by lukelbd** [comment]
Hi @pratiman-91, thanks for the PR! That bugfix is easy and I like the idea of "bounding boxes" for titles and a-b-c labels. When you get the chance can you fix the PEP8 errors? Also you might consider installing `pre-commit`, which will show you the PEP8 issues and prevent you from commiting until they are fixed, as mentioned in the [contribution guide](https://proplot.readthedocs.io/en/latest/contributions.html#preparing-pull-requests).

**Comment by lukelbd** [comment]
(Fixes #234)

**Comment by lukelbd** [comment]
Apparently I'm allowed to edit your PR myself (never did that before!). This was close to being ready anyway so I decided to fix the issues myself. Thanks again, merging now

**Comment by lukelbd** [comment]
I made some improvements to this feature on master (4288a73e):

1. "Borders" are still used by default (because IMO borders are less obtrusive and I see big no reason to change the default).
2. By default a square bounding box is drawn perfectly flush against the subplot edge.
3. There are new `title.bboxpad` and `abc.bboxpad` options to control padding.
4. Turning on `title.bbox` turns off `title.border`, and vice versa. You cannot have both of them on at the same time... which I imagine is what users will want 99% of the time.

Here's a nice example with these new features:

```python
import proplot as plot
fig, ax = plot.subplots(ncols=2)
print(plot.rc.abcborder)  # prints True
ax.contourf(np.random.rand(10, 10))
ax.format(abc=True, abcloc='ul', abcstyle='A.', abcbbox=True)  # temporarily sets border to False
```

tmp

**Comment by pratiman-91** [comment]
Looks good.
Thanks!

**Pull request merged**
