### PR TITLE
Organize documentation and sync ipython notebooks instead of nbconvert-generated RST files

### PR DESCRIPTION
**Pull request by lukelbd**
This will implement #32. I plan to sync ipython notebooks, have sphinx generate cell output **automatically** (and use this to automatically test changes, as an addendeum to scripts in `tests`, like [climpred](bradyrx/climpred) does), and use the auto-generated output in the documentation. Will also require more judicious merges/pushes to master, because the time for sphinx to generate documentation will probably go from ~1 minute to something like 5-10 minutes.

### CODE REVIEW

**Comment by lukelbd** [comment]
This PR will also clean up the documentation layout and make it look more like other readthedocs projects, e.g. [xarray](http://xarray.pydata.org) and [climpred](http://climpred.readthedocs.io). There will be three sections:

* **Getting Started**: Splits up some of the text in the README, and add some new sections like FAQ, "Why ProPlot" (where I get philosophical, talk about some fundamental limitations of matplotlib API and how I address them, etc.), definitely a dedicated "Installation" section with instructions for `pip` and `conda`.
* **User Guide**: Mostly contains the content of current "Overview", but might flesh out certain sections some more, and divide things up into more pages (e.g. a "Colorbars and legends" page).
* **Help & Reference**: Includes What's new changelog (also... I will start keeping a changelog), API Reference in its own section (will no longer have the subsections laid out in the main sidebar), Contributing Instructions, and maybe an External Links page to related projects.

**Comment by lukelbd** [comment]
As for the limitations section these are the first things that come to mind.

* Power users / academics generally want to change a ton of plot setting all at once, but to do this required a bunch of one-liner setters and getters (ProPlot has "format") and verbose class names (ProPlot has constructor functions like "Locator", "Formatter", ...).
* Gridspec requires fixed spacing between adjacent rows and columns which makes "tight layout" algorithms clumsy (note: should **add a tight layout option** that keeps spaces constant).
* Certain backends require figure size to be fixed and cannot be changed at drawtime by the "tight layout" algorithm. Got this to work with the static inline backend (simple fix) and the Qt popup backend (only fixable because of a sketchy detail in its implementation; might break someday), but it is unfixable for the "notebook" and "macosx" backends, and possibly other popup backends.

Also there are some *ProPlot* limitations I need to figure out.

* There is an "Artist.set" method, which makes `format` kind of redundant, but it is quite hidden and not at all recommended in examples. I think the problem is its usage is implicit/undocumented... its valid keyword args are any `name` that has an `Axes.set_name` method. Perhaps all features should be implemented as new "setter" methods, while use of `format` is highly encouraged and its arguments are explicitly documented.
* ProPlot immediately updates default settings with a `.proplotrc` file on import. This conflicts with people who have their own edits to `matplotlibrc` or use "style sheets". In the future ProPlot should respect user settings.

**Comment by lukelbd** [comment]
Also the new **User Guide** may have the following sections.

* Creating figures
* Customizing figures
* Tight layout
* Colorbars and legends
* Color usage
* X and Y axis settings
* Projection axes
* Xarray and pandas integration
* 2D plotting commands
* 1D and statistical plotting commands

There are a lot of features that are introduced way too quickly / probably go over people's heads, need to take more time introducing them.

**Comment by lukelbd** [comment]
Switching focus to this branch now. The main thing will be syncing ipython notebooks so that contributors can add/edit examples, and performing automatic testing with nbsphinx.

**Comment by bradyrx** [comment]
FYI you can add a `readthedocs` build test on your PR now. See "Getting Started" [here](https://blog.readthedocs.com/building-docs-for-pull-requests/). You just email them and they'll add this repo to their beta access.

It will automatically add `readthedocs` as a check. It will start showing up on your next pushed commit after you hear back from them (and on all new PRs). Then you can see on this isolated PR if it builds the docs without breaking and you can click a link to see what they look like.

Saves headaches for weird dependency things on the docs that you don't catch here.

**Comment by lukelbd** [comment]
Awesome, thanks for the tip. I'll do that.

**Comment by lukelbd** [comment]
The force push removes commited ipython notebook inline figure output. This was accidentally commited because `nbstripout` was not configured properly, and it increased the repo size by about 100MB! There are now also instructions for configuring `nbstripout` for new contributors in `HOWTOCONTRIBUTE.rst`, and a new local `.gitconfig` filter setup that makes the `nbstripout` commands verbose so you always know they are working.

Anyway, really excited about this branch! It significantly cleans up and fleshes out the documentation, and it adds a brand new minimal RTD theme with a light-dark mode toggle at the top of very page.

**Comment by lukelbd** [comment]
Beautiful. We *finally* have some basic testing (`make html` with `nbsphinx` on every PR) and the documentation looks so much better. Hopefully RTD has no issues; merging now.

**Comment by lukelbd** [comment]
RTD had memory usage issues. New docs should be live after readthedocs/readthedocs.org#6412 is resolved.

**Pull request merged**
