### PR TITLE
Compatibility with mpl v3.9.2 (latest)

### PR DESCRIPTION
**Pull request by cvanelteren**
Continuation of #458 and #450. This PR makes it up-to-date with the latest mpl version. 
It passes the generate unittests from #458, I will do some finalize testing since the colormaps are the major change in the last couple of mpl versions.

### CODE REVIEW

**Comment by cvanelteren** [comment]
- TODO fix docs

**Comment by cvanelteren** [comment]
Just an update: a lot of things are broken, but on the bright side some things are working. I don't yet understand how to properly override the existing colormap registry to include the local maps that are added by proplot. The main things that are added by proplot (next to colormaps) are the ability to lookup without case sensitivity. 

<details> <summary> current errors </summary>

```
=========================================================== short test summary info ===========================================================
FAILED proplot/tests/test_1dplots.py::test_bar_vectors - TypeError: alpha must be numeric or None, not <class 'numpy.ndarray'>
FAILED proplot/tests/test_1dplots.py::test_boxplot_colors - TypeError: Axes.violinplot() got an unexpected keyword argument 'hatches'
FAILED proplot/tests/test_1dplots.py::test_boxplot_vectors - TypeError: Axes.boxplot() got an unexpected keyword argument 'hatch'
FAILED proplot/tests/test_1dplots.py::test_scatter_alpha - Failed: DID NOT WARN. No warnings of type (<class 'proplot.internals.warnings.ProplotWarning'>,) were emitted.
FAILED proplot/tests/test_2dplots.py::test_colormap_vcenter - AttributeError: PolyQuadMesh.set() got an unexpected keyword argument 'vcenter'
FAILED proplot/tests/test_2dplots.py::test_autodiverging2 - AttributeError: PolyQuadMesh.set() got an unexpected keyword argument 'vcenter'
FAILED proplot/tests/test_axes.py::test_panels_suplabels - AttributeError: CartesianAxes.set() got an unexpected keyword argument 'refwidth'
FAILED proplot/tests/test_colorbar.py::test_segmented_norm_center - TypeError: SegmentedNorm.__init__() got an unexpected keyword argument 'vcenter'
FAILED proplot/tests/test_format.py::test_ignored_keywords - AttributeError: module 'proplot.tests' has no attribute 'warns'
FAILED proplot/tests/test_format.py::test_patch_format - KeyError: "'_magma_copy_r' is not a known colormap name"
FAILED proplot/tests/test_format.py::test_multi_formatting - AttributeError: '_LonAxis' object has no attribute 'axis_name'
FAILED proplot/tests/test_format.py::test_inner_title_zorder - KeyError: "'_magma_copy_r' is not a known colormap name"
FAILED proplot/tests/test_format.py::test_axes_colors - AttributeError: '_LonAxis' object has no attribute 'axis_name'
FAILED proplot/tests/test_format.py::test_locale_formatting - locale.Error: unsupported locale setting
FAILED proplot/tests/test_integration.py::test_pint_quantities - NameError: name 'pint' is not defined
FAILED proplot/tests/test_integration.py::test_seaborn_hist - TypeError: kdeplot() takes from 0 to 1 positional arguments but 2 positional arguments (and 1 keyword-only argument) were given
FAILED proplot/tests/test_projections.py::test_aspect_ratios - AttributeError: '_LonAxis' object has no attribute 'axis_name'
FAILED proplot/tests/test_projections.py::test_cartopy_labels - AttributeError: '_LonAxis' object has no attribute 'axis_name'
FAILED proplot/tests/test_projections.py::test_cartopy_contours - AttributeError: '_LonAxis' object has no attribute 'axis_name'
FAILED proplot/tests/test_projections.py::test_cartopy_manual - AttributeError: '_LonAxis' object has no attribute 'axis_name'
FAILED proplot/tests/test_projections.py::test_projection_dicts - AttributeError: '_LonAxis' object has no attribute 'axis_name'
=========================================== 21 failed, 88 passed, 4 skipped, 60 warnings in 19.99s ============================================
```

</details>

**Comment by cvanelteren** [comment]
@bradyrx perhaps you could look into the errors regarding geopy. I am not too familiar with geoaxes, but  the errors seem relatively straight forward if you are aware of those kind of axes.

**Comment by cvanelteren** [comment]
Starting to look good

<details> <summary> errors left to fix </summary>

```
================================================================== short test summary info ===================================================================
FAILED proplot/tests/test_format.py::test_patch_format - KeyError: "'_magma_copy_r' is not a known colormap name"
FAILED proplot/tests/test_format.py::test_multi_formatting - AttributeError: '_LonAxis' object has no attribute 'axis_name'
FAILED proplot/tests/test_format.py::test_inner_title_zorder - KeyError: "'_magma_copy_r' is not a known colormap name"
FAILED proplot/tests/test_format.py::test_axes_colors - AttributeError: '_LonAxis' object has no attribute 'axis_name'
FAILED proplot/tests/test_format.py::test_locale_formatting - locale.Error: unsupported locale setting
FAILED proplot/tests/test_integration.py::test_pint_quantities - NameError: name 'pint' is not defined
FAILED proplot/tests/test_integration.py::test_seaborn_hist - TypeError: kdeplot() takes from 0 to 1 positional arguments but 2 positional arguments (and 1 keyword-only argument) were given
FAILED proplot/tests/test_projections.py::test_aspect_ratios - AttributeError: '_LonAxis' object has no attribute 'axis_name'
FAILED proplot/tests/test_projections.py::test_cartopy_labels - AttributeError: '_LonAxis' object has no attribute 'axis_name'
FAILED proplot/tests/test_projections.py::test_cartopy_contours - AttributeError: '_LonAxis' object has no attribute 'axis_name'
FAILED proplot/tests/test_projections.py::test_cartopy_manual - AttributeError: '_LonAxis' object has no attribute 'axis_name'
FAILED proplot/tests/test_projections.py::test_projection_dicts - AttributeError: '_LonAxis' object has no attribute 'axis_name'
FAILED proplot/tests/test_subplots.py::test_reference_aspect - assert False
=================================================== 13 failed, 92 passed, 7 skipped, 66 warnings in 35.09s ================================================
```

**Comment by cvanelteren** [comment]
For those interested in giving it a spin, the day to day running works fine and I don't run into issues -- that said I do not use geoaxes. In stall by cloning the fork and installing i through there. I am Running python 3.12.

**Comment by didi-maru** [comment]
@cvanelteren tank you!
I tried to make geoaxes work with your fork, it seems that very few changes were necessary (see https://github.com/didi-maru/proplot/commit/32bf3ddb0fd5c082d2e53a8df6898f11ce4c5732)
I tested with Python 3.10 mpl 3.9.1 and cartopy 0.23.0. 
<details>

<summary>tests results</summary>

```
============================================================================================== short test summary info ===============================================================================================
FAILED proplot/tests/test_1dplots.py::test_boxplot_vectors - ValueError: operands could not be broadcast together with shapes (10,) (20,)
FAILED proplot/tests/test_format.py::test_patch_format - KeyError: "'_magma_copy_r' is not a known colormap name"
FAILED proplot/tests/test_format.py::test_multi_formatting - KeyError: "'_magma_copy_r' is not a known colormap name"
FAILED proplot/tests/test_format.py::test_inner_title_zorder - KeyError: "'_magma_copy_r' is not a known colormap name"
FAILED proplot/tests/test_format.py::test_locale_formatting - locale.Error: unsupported locale setting
FAILED proplot/tests/test_imshow.py::test_inbounds_data - KeyError: "'_magma_copy_r' is not a known colormap name"
FAILED proplot/tests/test_imshow.py::test_colorbar - KeyError: "'_magma_copy_r' is not a known colormap name"
FAILED proplot/tests/test_integration.py::test_pint_quantities - NameError: name 'pint' is not defined
FAILED proplot/tests/test_integration.py::test_keep_guide_labels - KeyError: "'_magma_copy_r' is not a known colormap name"
FAILED proplot/tests/test_integration.py::test_seaborn_swarmplot - KeyError: "'_magma_copy_r' is not a known colormap name"
FAILED proplot/tests/test_integration.py::test_seaborn_hist - TypeError: kdeplot() takes from 0 to 1 positional arguments but 2 positional arguments (and 1 keyword-only argument) were given
FAILED proplot/tests/test_subplots.py::test_reference_aspect - assert np.False_
============================================================================== 12 failed, 93 passed, 7 skipped, 245 warnings in 33.43s ===============================================================================
```

</details>

**Comment by cvanelteren** [comment]
@didi-maru Nice team work! Just added it to this PR ;-)! On wards and upwards!

**Comment by cvanelteren** [comment]
All test pass  :partying_face: 
image

There is still some work to do however. 
- We cannot update numpy to 2.0 due to a dask issue that some of the tests (and I am guessing cartopy users require).
- There are some depecration warnings I would like to clean up before submitting
- Looking through the generated baselines there are some funky oddities that would require some closer inspection but it is looking good ;-)!

**Comment by cvanelteren** [comment]
Note to future me: 
- Check some of the imshow baselines, they have extra white space that shouldn't be there (could be the tests)
- Check the ticker, some of the tickers are spaced out too tightly (could be the tests).
- Replace some of the statistical tests with the ones from the docs (there is no reference currently how they should look and they look odd).

**Comment by riley-brady** [comment]
Awesome job so far!! Am I understanding that this is the focus PR and includes all of #458 and more?

I would say to add an explicit automated Github Action to this PR to run all of this unit tests so it is appended to the PR. Is that something you have experience with? Happy to add this if needed.

Would think we'd want to add
* Standard testing for `proplot` install on various architectures (e.g. https://github.com/pangeo-data/climpred/blob/main/.github/workflows/climpred_installs.yml)
* Variety of unit testing, using a matrix of `matplotlib`, `cartopy`, and `python` installs. E.g. https://github.com/pangeo-data/climpred/blob/main/.github/workflows/climpred_testing.yml or better examples out there.
* Some sort of nightly or weekly cron job that runs upstream against the latest `matplotlib` and `cartopy`. I think a lot of the open source standard packages have examples of these.

**Comment by riley-brady** [comment]
See https://github.com/readthedocs/readthedocs.org/issues/11173 potentially for `readthedocs` breaks.

Another level of testing will be to add docs testing so the docs examples aren't out of line with where the package goes. Probably overkill to add that to this PR. More important is unit testing working and that `proplot` works with modern package versions.

**Comment by cvanelteren** [comment]
This PR is intended to do two things

- To add unittests to proplot
- To make it up-to-date with the latest mpl

In hindsight I should have separated these more cleanly. I can have a look if it is still possible to separate them so we can also have backwards compatible unittest from 3.4.2 onwards.

I am going to have a look at cmasher how they handle the new colormap registration as this is still not working correctly. Second, there are some functions that produce odd results (pcolormesh for example). The axes objects also loose there ability to slice in a 2D manner. Lastly, the colorbars are not aligned with the axis object when viewing it in qt5 for example, but they are aligned when saving the figure, guessing there is some tight_layout shenanigans going on. Other than those, everything has been running smoothly, I am daily driving this to see if I can spot some obvious errors during my day-to-day.

**Comment by cvanelteren** [comment]
I will look into the points you addressed @riley-brady  when the above is fixed. Then I would feel more comfortable that proplot is compatible with the latest mpl.

**Comment by cvanelteren** [comment]
Note to self:
Colormasher just uses the default register functions (see https://github.com/1313e/CMasher/blob/b5b4ed6d9ce7a1b2811664afd8e1ffe836603e82/cmasher/utils.py#L1391C1-L1403C57)

**Comment by cvanelteren** [comment]
Not really sure what causes the differences with pcolor/pcolormesh. For example `test_auto_diverging1` creates:

image
but when recreating in a separate py file I get the plot 
test

so somehow when exporting with pytest mpl it generates this difference that I cannot reproduce on the proplot side.

**Comment by cvanelteren** [comment]
Note to self: all tests pass at the moment. The doctests, however, still create some errors. The Colormap registration is now properly handled.

**Comment by cvanelteren** [comment]
@riley-brady  see comment above

**Comment by cvanelteren** [comment]
Converting this back to draft; I need to look at the colormap again, and preserve the original names of the lookup instead of forcing the maps.

**Comment by cvanelteren** [comment]
@riley-brady  I got proplot to build again, but running into some env issues; will figure it out eventually. Locally some doctests fail in the geoaxes. They will needs some TLC regarding the keywords, other than that things are looking pretty good and close to done.

**Comment by riley-brady** [comment]
Thanks for continuing to push on this!

**Comment by cvanelteren** [comment]
I am still trying to figure out what causes the issue with the theme. I temporarily set it to the default theme and then all the tests pass including the doctests.
:bell:  Pinging @lukelbd  :bell:

**Comment by riley-brady** [comment]
I think if it's just a readthedocs theme I wouldn't worry about it for now. If all of your unit testing is passing and all looks good here, I think we should just advertise across the issues and PRs for people to install:

`pip install git+https://github.com/proplot-dev/proplot.git@refs/pull/459/head`

until @lukelbd merges this into a proper release.

Incredible work! I haven't gotten to test in our repos just yet. Really exciting though

**Comment by cvanelteren** [comment]
The code is now completely compatible. The docs are getting built properly (locally) but hangs in the env from read the docs. This causes a timeout. Locally that step also takes long, but eventually finishes. I have the suspicion this is causes by the projections tested at the end.

**Comment by cvanelteren** [comment]
Ready for merge

**Comment by riley-brady** [comment]
Setting up environment for testing, with a bunch of bleeding edge modern package versions with python 3.11:

```bash
mamba create -c conda-forge -n pplot_test python=3.11 matplotlib cartopy numpy pandas xarray
```

Trying to install from most recent official `proplot` release:


```bash
conda activate pplot_test
mamba install -c conda-forge proplot
```

```python-traceback
The following package could not be installed
└─ proplot is installable and it requires
   ├─ matplotlib <3.5.0a0  with the potential options
   │  ├─ matplotlib [3.3.2|3.3.3|...|3.4.3] would require
   │  │  └─ python >=3.8,<3.9.0a0 , which can be installed;
   │  ├─ matplotlib [3.3.2|3.3.3|...|3.4.3] would require
   │  │  └─ python >=3.9,<3.10.0a0 , which can be installed;
   │  └─ matplotlib 3.4.3 would require
   │     └─ python >=3.10,<3.11.0a0 , which can be installed;
   └─ matplotlib-base <3.5.0a0  with the potential options
      ├─ matplotlib-base [3.3.2|3.3.3|...|3.4.3] would require
      │  └─ python >=3.8,<3.9.0a0 , which can be installed;
      ├─ matplotlib-base [3.3.2|3.3.3|...|3.4.3] would require
      │  └─ python >=3.9,<3.10.0a0 , which can be installed;
      └─ matplotlib-base 3.4.3 would require
         └─ python >=3.10,<3.11.0a0 , which can be installed.
```

Now with your branch:

```bash
pip install git+https://github.com/proplot-dev/proplot.git@refs/pull/459/head
```

Install successful!! 🎉 

Quick test:

```python
import xarray as xr
import numpy as np
import proplot as plot

xr.DataArray(np.random.random((50, 50)), dims=['x', 'y']).plot()
```

Screenshot 2024-08-18 at 4 36 04 PM

**Comment by riley-brady** [comment]
Awesome job @cvanelteren!! Excited for @lukelbd to merge this in when he has time. In the meantime will broadcast on old issues and PRs to install this way.

**Comment by Holmgren825** [comment]
Hey, this is wonderful! Very happy to be able to update soon. I tried this out quickly and there seems to be a problem with the integration with cartopy. For instance:
```python
fig, ax = pplt.subplots(proj="pcarree")
```
works as expected, but trying a few different projections such as `"robin"`, `"merc"` or `"npstere"` does not and throws an error. 

<details>
  <summary>Click to expand trace</summary>

 ---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File [~/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/matplotlib/figure.py:1787](http://localhost:8888/lab/tree/dev/etc/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/matplotlib/figure.py#line=1786), in FigureBase.get_tightbbox(self, renderer, bbox_extra_artists)
   1786 try:
-> 1787     bbox = ax.get_tightbbox(
   1788         renderer, bbox_extra_artists=bbox_extra_artists)
   1789 except TypeError:

File [~/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/proplot/axes/geo.py:1326](http://localhost:8888/lab/tree/dev/etc/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/proplot/axes/geo.py#line=1325), in _CartopyAxes.get_tightbbox(self, renderer, *args, **kwargs)
   1324     self._gridliners = []
-> 1326 return super().get_tightbbox(renderer, *args, **kwargs)

File [~/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/proplot/axes/base.py:2780](http://localhost:8888/lab/tree/dev/etc/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/proplot/axes/base.py#line=2779), in Axes.get_tightbbox(self, renderer, *args, **kwargs)
   2779     self.indicate_inset_zoom()
-> 2780 self._tight_bbox = super().get_tightbbox(renderer, *args, **kwargs)
   2781 return self._tight_bbox

File [~/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/cartopy/mpl/geoaxes.py:499](http://localhost:8888/lab/tree/dev/etc/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/cartopy/mpl/geoaxes.py#line=498), in GeoAxes.get_tightbbox(self, renderer, *args, **kwargs)
    497 self._draw_preprocess(renderer)
--> 499 return super().get_tightbbox(renderer, *args, **kwargs)

File [~/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/matplotlib/_api/deprecation.py:457](http://localhost:8888/lab/tree/dev/etc/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/matplotlib/_api/deprecation.py#line=456), in make_keyword_only.<locals>.wrapper(*args, **kwargs)
    452     warn_deprecated(
    453         since, message="Passing the %(name)s %(obj_type)s "
    454         "positionally is deprecated since Matplotlib %(since)s; the "
    455         "parameter will become keyword-only %(removal)s.",
    456         name=name, obj_type=f"parameter of {func.__name__}()")
--> 457 return func(*args, **kwargs)

File [~/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/matplotlib/axes/_base.py:4499](http://localhost:8888/lab/tree/dev/etc/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/matplotlib/axes/_base.py#line=4498), in _AxesBase.get_tightbbox(self, renderer, call_axes_locator, bbox_extra_artists, for_layout_only)
   4498 for a in bbox_artists:
-> 4499     bbox = a.get_tightbbox(renderer)
   4500     if (bbox is not None
   4501             and 0 < bbox.width < np.inf
   4502             and 0 < bbox.height < np.inf):

File [~/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/cartopy/mpl/gridliner.py:1243](http://localhost:8888/lab/tree/dev/etc/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/cartopy/mpl/gridliner.py#line=1242), in Gridliner.get_tightbbox(self, renderer)
   1242 self._draw_gridliner(renderer=renderer)
-> 1243 bboxes = [c.get_tightbbox(renderer=renderer)
   1244           for c in self.get_visible_children()]
   1245 if bboxes:

File [~/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/cartopy/mpl/gridliner.py:1243](http://localhost:8888/lab/tree/dev/etc/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/cartopy/mpl/gridliner.py#line=1242), in <listcomp>(.0)
   1242 self._draw_gridliner(renderer=renderer)
-> 1243 bboxes = [c.get_tightbbox(renderer=renderer)
   1244           for c in self.get_visible_children()]
   1245 if bboxes:

File [~/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/matplotlib/artist.py:365](http://localhost:8888/lab/tree/dev/etc/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/matplotlib/artist.py#line=364), in Artist.get_tightbbox(self, renderer)
    350 """
    351 Like `.Artist.get_window_extent`, but includes any clipping.
    352 
   (...)
    363     Returns None if clipping results in no intersection.
    364 """
--> 365 bbox = self.get_window_extent(renderer)
    366 if self.get_clip_on():

File [~/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/matplotlib/collections.py:311](http://localhost:8888/lab/tree/dev/etc/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/matplotlib/collections.py#line=310), in Collection.get_window_extent(self, renderer)
    308 def get_window_extent(self, renderer=None):
    309     # TODO: check to ensure that this does not fail for
    310     # cases other than scatter plot legend
--> 311     return self.get_datalim(transforms.IdentityTransform())

File [~/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/matplotlib/collections.py:270](http://localhost:8888/lab/tree/dev/etc/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/matplotlib/collections.py#line=269), in Collection.get_datalim(self, transData)
    269 if not transform.is_affine:
--> 270     paths = [transform.transform_path_non_affine(p) for p in paths]
    271     # Don't convert transform to transform.get_affine() here because
    272     # we may have transform.contains_branch(transData) but not
    273     # transforms.get_affine().contains_branch(transData).  But later,
    274     # be careful to only apply the affine part that remains.

File [~/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/matplotlib/collections.py:270](http://localhost:8888/lab/tree/dev/etc/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/matplotlib/collections.py#line=269), in <listcomp>(.0)
    269 if not transform.is_affine:
--> 270     paths = [transform.transform_path_non_affine(p) for p in paths]
    271     # Don't convert transform to transform.get_affine() here because
    272     # we may have transform.contains_branch(transData) but not
    273     # transforms.get_affine().contains_branch(transData).  But later,
    274     # be careful to only apply the affine part that remains.

File [~/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/matplotlib/transforms.py:2445](http://localhost:8888/lab/tree/dev/etc/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/matplotlib/transforms.py#line=2444), in CompositeGenericTransform.transform_path_non_affine(self, path)
   2444 elif not self._a.is_affine and self._b.is_affine:
-> 2445     return self._a.transform_path_non_affine(path)
   2446 else:

File [~/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/cartopy/mpl/geoaxes.py:175](http://localhost:8888/lab/tree/dev/etc/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/cartopy/mpl/geoaxes.py#line=174), in InterProjectionTransform.transform_path_non_affine(self, src_path)
    174 transformed_geoms = []
--> 175 geoms = cpatch.path_to_geos(src_path)
    177 for geom in geoms:

File [~/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/cartopy/mpl/patch.py:210](http://localhost:8888/lab/tree/dev/etc/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/cartopy/mpl/patch.py#line=209), in path_to_geos(path, force_ccw)
    208 if geom_collection and all(isinstance(geom, sgeom.LineString) for
    209                            geom in geom_collection):
--> 210     geom_collection = [sgeom.MultiLineString(geom_collection)]
    212 # Remove any zero area Polygons

File [~/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/shapely/geometry/multilinestring.py:60](http://localhost:8888/lab/tree/dev/etc/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/shapely/geometry/multilinestring.py#line=59), in MultiLineString.__new__(self, lines)
     58     return shapely.from_wkt("MULTILINESTRING EMPTY")
---> 60 return shapely.multilinestrings(subs)

File [~/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/shapely/decorators.py:77](http://localhost:8888/lab/tree/dev/etc/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/shapely/decorators.py#line=76), in multithreading_enabled.<locals>.wrapped(*args, **kwargs)
     76         arr.flags.writeable = False
---> 77     return func(*args, **kwargs)
     78 finally:

File [~/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/shapely/creation.py:393](http://localhost:8888/lab/tree/dev/etc/miniforge3/envs/ppl_dev/lib/python3.11/site-packages/shapely/creation.py#line=392), in multilinestrings(geometries, indices, out, **kwargs)
    392 if indices is None:
--> 393     return lib.create_collection(geometries, typ, out=out, **kwargs)
    394 else:

TypeError: ufunc 'create_collection' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''


</details>

**Comment by cvanelteren** [comment]
@Holmgren825  I cannot reproduce this error here locally. It also points to a shapely issue rather than proplot. I have cartopy 0.23.0 installed, what version are you running?

**Comment by cvanelteren** [comment]
The projections in the docs also point to it working fine (see https://proplot--459.org.readthedocs.build/en/459/projections.html). The environment is currently rather unconstrained and would love to add the information in there to prevent a build issue like yours from happening.

**Comment by Holmgren825** [comment]
Wierd. I had the same version. But if I upgrade to shapely 2.0.6 things work.

**Comment by cvanelteren** [comment]
Ah thanks for reminding me. Numpy should be held back due to some dependency issues with xarray. Fixed in latest commit

**Comment by huddao** [comment]
canot install:
```
$ pip install git+https://github.com/proplot-dev/proplot.git@refs/pull/459/head
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting git+https://github.com/proplot-dev/proplot.git@refs/pull/459/head
  Cloning https://github.com/proplot-dev/proplot.git (to revision refs/pull/459/head) to /tmp/pip-req-build-0rm6thj_
  Running command git clone --quiet https://github.com/proplot-dev/proplot.git /tmp/pip-req-build-0rm6thj_
  WARNING: Did not find branch or tag 'refs/pull/459/head', assuming revision or ref.
  Running command git fetch -q https://github.com/proplot-dev/proplot.git refs/pull/459/head
  Running command git checkout -q f7524a24eef76f59b5d0fad56faac14e9fcf0846
  Resolved https://github.com/proplot-dev/proplot.git to commit f7524a24eef76f59b5d0fad56faac14e9fcf0846
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: importlib-metadata in /public/home/hzc/soft/anaconda3-2023/envs/geos-chem-3.11/lib/python3.11/site-packages (from proplot==0.9.5.post425) (8.4.0)
Requirement already satisfied: zipp>=0.5 in /public/home/hzc/soft/anaconda3-2023/envs/geos-chem-3.11/lib/python3.11/site-packages (from importlib-metadata->proplot==0.9.5.post425) (3.20.0)
```

**Comment by cvanelteren** [comment]
@ huddao  I don't see any errors?

**Comment by huddao** [comment]
@cvanelteren The version is 'proplot==0.9.5.post425', I'm not sure this is the correct version.

**Comment by cvanelteren** [comment]
The correct version should be tagged as `v0.9.91`. Try installing it from here:

` pip install git+https://github.com/cvanelteren/proplot.git@v0.9.91`

**Comment by huddao** [comment]
@cvanelteren The new version, thanks.

**Comment by huddao** [comment]
@cvanelteren Thanks!

**Comment by austin-hoover** [comment]
Any update on this? I'm posting analysis code for a paper and it would be great to reference the main proplot branch in the requirements.

**Comment by riley-brady** [comment]
Nothing that I've seen @austin-hoover. Still waiting on @lukelbd to come in and merge, as he is the only one with permissions. For now you will have to point to @cvanelteren's branch. You can always update your code repo linked to the paper at a later point and point back to a main release here.

**Comment by cvanelteren** [comment]
Any movement on this @lukelbd?

**Comment by austin-hoover** [comment]
Also PyPI doesn't allow direct links to GitHub repos, so projects on PyPI can't list working proplot version as a dependency right now.

**Comment by cvanelteren** [comment]
wanted to address the current status of proplot's development. With the recent lack of movement on this project, there's a genuine concern about potentially losing our valuable contributors. To prevent this, I'm proposing we restructure the project under a more collaborative, organization-based framework that would:

1. Facilitate continued development
2. Decentralize the pull request process
3. Enable broader community participation

Beginning in the new year, I'm prepared to take on a more active leadership role in this initiative. My plan includes forking the repository to maintain development momentum, but I'm committed to keeping communication channels open with @lukelbd and other stakeholders.

I'd like to extend an invitation to all interested contributors to join this effort. If you're passionate about proplot's future and want to be part of its continued development, please reach out to discuss how we can collaborate effectively.

Together, we can ensure proplot remains a vibrant and well-maintained project that serves its community's needs.

**Comment by riley-brady** [comment]
> I wanted to address the current status of proplot's development. With the recent lack of movement on this project, there's a genuine concern about potentially losing our valuable contributors. To prevent this, I'm proposing we restructure the project under a more collaborative, organization-based framework that would:
> 
> 1. Facilitate continued development
> 2. Decentralize the pull request process
> 3. Enable broader community participation
> 
> Beginning in the new year, I'm prepared to take on a more active leadership role in this initiative. My plan includes forking the repository to maintain development momentum, but I'm committed to keeping communication channels open with @lukelbd and other stakeholders.
> 
> I'd like to extend an invitation to all interested contributors to join this effort. If you're passionate about proplot's future and want to be part of its continued development, please reach out to discuss how we can collaborate effectively.
> 
> Together, we can ensure proplot remains a vibrant and well-maintained project that serves its community's needs.

Please keep us posted when you fork out and launch the project. My job has severely limited the time I have to directly contribute, but I can continue with scoping as I did here. Might have some opportunities to contribute directly as well. Thanks @cvanelteren and enjoy your well-earned vacation!

**Comment by beckermr** [comment]
@cvanelteren count me in on helping with dev as I can and I'd like to be a part of the effort. Also, I am cross-referencing the issue currently open on more sustainable development (https://github.com/proplot-dev/proplot/issues/452).

From the point of view of shipping a fork on conda-forge, it will be by far the easiest if the forked project gets a new name.

**Comment by cvanelteren** [comment]
Yes I agree @beckermr -- I already have a logo for it ;-). I will be in touch in the new year!

**Comment by pratiman-91** [comment]
@cvanelteren I am willing to help wherever I can. I like proplot, and it would be nice to see a continuous development along with the latest matplotlib.

**Comment by gepcel** [comment]
Any updates on this? Now matplolitb 3.9.3 is out. Would be nice to see continuous development along with the latest matplotlib.

**Comment by cvanelteren** [comment]
See thread above

**Comment by gepcel** [comment]
> See thread above

Thanks for your reply. I have followed this thread since the very beginning, and I'm eager to hear some updates on the forking repository and maintaining development. Maybe I'm not capable of helping, but I like this package.

Any way I'll just wait for the new year.

**Comment by jenchen95** [comment]
Thank you very much for your contribution, although I regret the single pull request review access, when reviewers are in the middle of a busy work schedule or vacation process, quality contributions like this can go unnoticed, which can wear down the enthusiasm for open source contributions.

**Comment by cvanelteren** [comment]
Continue discussion here https://github.com/cvanelteren/proplot/issues/1

**Comment by cvanelteren** [comment]
@gepcel this commit is compatible with mpl 3.9.3 (just tested) 
Development will continue here https://github.com/Ultraplot/ultraplot

Closing this issue for now and everyone is welcome on the forked repo

**Comment by cvanelteren** [comment]
`pip install ultraplot` is now live! :partying_face: 
Conda following soon :eyes:

**Pull request closed without merging**
