### PR TITLE
Replace "panels" with EdgeStack, permit working directly with add_subplot/GridSpec

### PR DESCRIPTION
**Pull request by lukelbd**
**Duplicate**: This branch was made before I know how to properly use git branches. It contained unrelated features that were subsequently copied into separate branches and individually merged into master. Its history is a cluster**** so I have replaced it with #110.

### CODE REVIEW

**Comment by bradyrx** [comment]
I think this is helpful too in the case that you don't have M x N axes to plot. I.e., the number of axes doesn't evenly divide into a square or rectangle. I've had to do this before, but I can't remember why. 

A good example would be if you're doing small multiples of some region or global variable over multiple decades. The 2010s row wouldn't fill all the way out.

**Comment by lukelbd** [comment]
@bradyrx This is actually already a feature -- see the [subplots "array" keyword arg](https://proplot.readthedocs.io/en/latest/api/proplot.subplots.subplots.html#proplot.subplots.subplots). Used in the examples from [this section](https://proplot.readthedocs.io/en/latest/intro.html#layout-and-numbering).

That's why I felt comfortable doing away with non-`f, axs = plot.subplots()` workflows, because `subplots` supports arbitrary layouts. Probably still a good idea though to let the user decide though, some people are much more used to the `add_subplot` workflow.

**Comment by lukelbd** [comment]
Oh, I see what you meant now. This is also an `array` feature: Just put a `0` in the array where you don't want to draw any axes.

**Comment by lukelbd** [comment]
This is coming along nicely. The next major change will be to allow `GridSpec` class to accept `left`, `right`, `wspace`, etc. in *physical units*. Previously this was relegated to `subplots()` but now that `subplots()` is not the only way to make figures, that doesn't make sense / caused a bunch of complications.

**Comment by lukelbd** [comment]
This turned out to be *really* complicated. Modifying the gridspec algorithm to work with physical units is simple -- I just need to fix `GridSpec.get_grid_positions()` (still not done yet). The issue is in letting users manipulate their own `GridSpec` objects and letting users pass gridspec spacing values to `plot.figure()` before the gridspec is necessarily created.

I needed to mimic the matplotlib approach of specifying default gridspec spacing on the *figure* with `Figure.subplots_adjust` and `matplotlib.figure.SubplotParams`, then allowing `proplot.GridSpec` spacing values that were not explicitly specified to inherit from the figure at draw-time. I made a `geometry_configurator` class to handle this. The class also does the various other figure layout calculations that were previously in ~10 hidden `Figure` methods. It's a much better cleaner I think, and keeps me from having to pollute the `Figure` with a ton of hidden methods.

However the next big issue is that when colorbars, legends, and axes panels are created, they secretly "insert a new column or row" by **destroying the existing gridspec and create a new one**. This means if users keep using the `GridSpec` object after adding a figure panel or something, its geometry is different from the figure gridspec, and an error will be raised (or if I didn't raise one, shit would get weird). There are two approaches to this.

1. Incorporate "panel" rows and columns into the definition of GridSpec itself. But then we regress back to having `GridSpec.__getitem__` obfuscate the "true" underlying gridspec dimensions and things generally get messy.
2. Use #46 -- stop drawing "panels" inside the GridSpec, and just draw them as "parasites" inside the space between primary subplots. This is less messy but more laborious -- it will require redesigning the "tight layout" algorithm to work with stacked parasite objects, figuring out how to lock them to main axes (probably similar to how "inset" axes are locked to main axes), and figuring out how to lock their physical widths. Basically will need to dive into transforms/bounding boxes more deeply -- I can also have to be smarter about the artists included in the respective Axes/Figure tight layout calculations.

I'm leaning toward \#2. It's sad that that I spent so much time working to implenent panels as part of the main gridspec rather than this "parasite" axes stuff... but I think this will eliminate the last really "hacky" part of proplot and is an important step to making this a real, robust matplotlib extension. Will just take some time.

**Comment by lukelbd** [comment]
This branch has a ways to go but I'm going to try to finish #47 first so I can finally allow contributors.

**Comment by lukelbd** [comment]
For permitting colorbars, legends, and text along arbitrary contiguous axes, I can write a helper function that accepts lists of *subplots* and makes sure their right/left/top/bottom edges are in alignment.

* When you call `axes_grid([...]).colorbar(...)` or `axes_grid([...]).legend(...)`, it will pass the axes in the container to this hidden method.
* When you call `Figure.colorbar(...)` or `Figure.legend(...)`, it will select the subplots lying along the figure edge and pass them to the hidden method.

**Comment by lukelbd** [comment]
#47 is done so this is now the priority again. Though I might take some time off (or at least scale way back) to work on a paper.

**Comment by lukelbd** [comment]
For implementing colorbars/legends/panels as "parasite axes", there is some existing similar code for this in the `axes_grid1` toolkit. I could borrow this code so that panel, colorbar, and legend long-axis coordinates are automatically updated when subplot positions change.

There are several advantages here.

*  Panels in the same row or column no longer have to be the same width, which can be a problem when you have legends + colorbars alongisde each other.
* It would be relatively straightforward to implement an `axes_grid` legend, colorbar, and text methods that draw legends and colorbars or labels along the sides of **arbitrary contiguous** axes, instead of just along the figure edge.
* We would no longer have to modify the underlying gridspec when inserting panels. Could delete the cumbersome `Figure._insert_rows_columns` function.
* Legends no longer have to belong to an empty, dummy axes -- we can just lock the legend position.
* Colorbars no longer have to belong to empty, dummy axes to extend them along <100% of the axes -- we just adjust the parent-relative long axis coordinates. This also eliminates all references to GridSpecFromSubplotSpec, which proplot's GridSpec tries to make obsolete.
* We can now implement `rowlabels` and `collabels` with the same API, allow "stacking" arbitrary outer text objects just like colorbars/legends/panels.

The difficulty is that I have to figure out how to specify axes bounds so that their long axis is *locked* to another axes (probably similar to the `inset_axes` locator) and their short axes has *locked* physical width (i.e. is not in physical units). Also, currently, the `tight_layout` algorithm works to separate panels and subplots alike by just inspecting axes in adjacent rows/columns of the gridspec. With this PR, an additional step in the algorithm that separates "stacked" objects will have to be written.

**Pull request closed without merging**
